name: hakaton
description: SLAM Visualizer
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  video_player: ^2.9.1
  file_picker: ^10.3.3
  webview_flutter: ^4.13.0
  yaml: ^3.1.3
  http: ^1.5.0
  usb_serial: ^0.5.2
  network_info_plus: ^7.0.0
  wifi_info_plugin_plus: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/three.js
    - assets/web/orbitcontrols.js
    - assets/html/visualizer.html